---
title: "Adult Cardiothoracic Anesthesiology" 
---

# 2024 - 2025

[PROTECTION - RCT Amino Acids for AKI in Cardiac Surgery; NEJM 2024](https://www.nejm.org/doi/full/10.1056/NEJMoa2403769)

* __Clinical Question__: In elective cardiac surgeries requiring CPB, does an IV infusion of amino acids (isopuramin 10%) therapy at the time of surgery compared to placebo (LR) decrease the incidence of postoperative AKI in the first week?

* __Methods + Results__: Multicenter RCT; The investigators measured baseline creatinine and defined a reasonable primary outcome, postoperative (0-7 days) AKI by KDIGO criteria. AKI had developed in 474 patients in the amino acid group (26.9%) and in 555 patients in the placebo group (31.7%) (RR = 0.85; 95% CI [0.77 to 0.94]; P=0.002). There were no differences in secondary outcome measures (Hospital and ICU LOS, RRT initiation, MV duration).

* __Take Away__: IV amino acids may reduce the risk of AKI after elective cardiac surgery. The study was well-designed and executed, but had limitations in patient demographics (external generalizability) and lack of additional indicators of AKI.


<br>

[ATACAS RCT: Stopping vs. Continuing Aspirin before Coronary Artery Surgery; NEJM 2016](https://www.nejm.org/doi/full/10.1056/NEJMoa1507688)

* __Clinical Question__: Does taking aspirin before coronary artery bypass surgery reduce the risk of death or thrombotic complications (nonfatal myocardial infarction, stroke, pulmonary embolism, renal failure, or bowel infarction)?

* __Methods + Results__: After patients were randomized to aspirin or placebo and monitored for 30 days post coronary artery bypass surgery, the data showed that there were no significant differences in the primary outcome (death or thrombotic events) or secondary outcomes (death, myocardial infarction, renal failure, pulmonary embolism, bowel infarction, re-op for hemorrhage, cardiac tamponade).

* __Take Away__: Aspirin is safe to use in the perioperative period of coronary artery bypass surgery.


<br>

[Dexamethasone for Cardiac Surgery: Practice Preference Comparative Effectiveness Trial; Anesthesiology 2024](https://pubs.asahq.org/anesthesiology/article/141/5/859/141590/Dexamethasone-for-Cardiac-Surgery-A-Practice)

* __Clinical Question__: In adults under 75 years old undergoing elective cardiac surgery requiring CPB, does administration of high dose dexamethasone increase the number of home days after surgery and decrease the risk of serious complications?

* __Methods + Results__: Patients were randomized prior to consent 2:1 favoring site standard of care, and followed for 30 days. In the treatment group, patients were administered one dose of dexamethasone 1mg/kg up (up to 100mg). There was no significant difference in the number of days alive and at home after surgery.

* __Take Away__: High dose dexamethasone may decrease ICU LOS, but does not increase the number of alive and home days, nor significantly affect the risk of serious complications, after cardiac surgery.


<br>

[Extracorporeal Blood Purification and AKI - SIRAKIO2 RCT; JAMA 2024](https://jamanetwork.com/journals/jama/fullarticle/2824929)

* __Clinical Question__: Does extracorporeal blood purification (EBP) during cardiopulmonary bypass (CPB) reduce the risk of acute kidney injury (AKI) after nonemergent cardiac surgery?

* __Methods + Results__: In this double-blinded RCT, the investigators compared the rate of AKI by KDIGO criteria among cardiac surgery patients who underwent EBP through an acrylonitirile-sodium methallylsulfonate/polyethylenimine membrane during CPB vs those who underwent CPB only, finding a statistically significant reduction in AKI in the EBP cohort (28.4%,  CI 21.7-35.8% vs 39.7%, CI 32.3-47.3, P = 0.03).

* __Take Away__: This study demonstrates that EBP may reduce the risk of AKI after CPB, although the study is not sufficiently powered to determine whether secondary clinical outcomes are changed as a result, whether the outcome was due to the use of an EBP membrane vs the use of CRRT in which the membrane was inserted, or whether the use of  EBP is economically justified for the clinical effect size.

<br>

[PROTECTED TAVR - Cerebral Embolic Protection during TAVR; NEJM 2022](https://www.nejm.org/doi/full/10.1056/NEJMoa2204961)

* __Clinical Question__: Does the use of the Sentinel device during TAVR decrease the incidence of periprocedural stroke?

* __Methods + Results__: Multicenter prospective randomized controlled trial of 3000 patients randomized to Sentinel or no Sentinel during TAVR who underwent preprocedural and postprocedural neurologic examination to evaluate for periprocedural stroke. There was no significant difference in the incidence of periprocedural stroke in the Sentinel and no Sentinel groups.

* __Take Away__: While Sentinel use did not decrease the incidence of periprocedural stroke, it did decrease the incidence of debilitating stroke and was shown to be safe. 

<br>

[Safety and efficacy of colchicine for prevention of postop a.fib.in patients undergoing cardiac surgery: meta-analysis; EP Europace 2023](https://pmc.ncbi.nlm.nih.gov/articles/PMC10318383/)

* __Clinical Question__: Is colchicine safe and effective at preventing postoperative atrial fibrillation after cardiac surgery when compared to placebo?

* __Methods + Results__: This is a systematic literature review and meta-analysis of eight RCTs that showed, in comparison to placebo,  colchicine administration reduced risk of postoperative atrial fibrillation (RR 0.70, 95% CI [0.59 - 0.82], I^2 =0%, high certainty evidence), conferred a higher risk of nausea, vomiting, and diarrhea (RR 2.20, 95% CI [1.38 - 3.51], I^2 = 55%, high certainty evidence), and had a higher but non-significant difference in rate of drug discontinuation (RR 1.33, 95% CI [0.93 - 1.89], I^2 =0%, moderate quality evidence).

* __Take Away__: Peri-operative colchicine administration reduces post-operative atrial fibrillation in cardiac surgery patients, but use may be limited by a lack of data on effective dosing, duration, and comparison to other antiarrhythmic agents.

<br>

[FARES-II: Prothrombin Complex Concentrate vs Frozen Plasma for Coagulopathic Bleeding in Cardiac Surgery; JAMA 2025](https://jamanetwork.com/journals/jama/fullarticle/2832096?resultClick=1)

* __Clinical Question__: Is PCC (1500 IU for ≤60 kg; 2000 IU for >60 kg) noninferior and/or superior to FFP (3 U for ≤60 kg; 4 U for >60 kg) in achieving effective hemostasis in patients who have coagulopathic bleeding while undergoing cardiac surgery?

* __Methods + Results__: This unblinded randomized noninferiority trial involving 420 patients from centers in the US and Canada found that patients treated with PCC had effective hemostasis in 77.9% of cases vs. 60.4% of cases treated with FFP (difference, 17.6%; 95% CI, 8.7%-26.4%; P < .001); PCC treated patients also received fewer RBC, platelet, and non-investigational FFP transfusions, with fewer patients from the PCC group experiencing serious adverse events and AKI.

* __Take Away__: PCC is safe and superior to FFP in achieving hemostasis and can decrease transfusion requirements in patients who require coagulation factor repletion during cardiac surgery.

<br>

[B-FREE: BZD-Free Cardiac Anesthesia for Reduction of Postoperative Delirium; JAMA 2025](https://jamanetwork.com/journals/jamasurgery/fullarticle/2829514)

* __Clinical Question__: Does an institutional policy of restricted intraoperative benzodiazepine administration during cardiac surgery reduce the incidence of postoperative delirium?

* __Methods + Results__: This was a multiperiod, patient- and assessor-blinded, cluster randomized crossover trial at 20 North American cardiac surgical centers (total of 19,768 patients) that evaluated the incidence of postoperative delirium, as detected in routine care up to 72 hrs after surgery, when an institutional policy of restrictive benzodiazepine use (no benzodiazepines) or liberal benzodiazepine use (at least 0.03mg/kg IBW midazolam equivalent) was used during cardiac surgery. There was no statistically significant difference in delirium between restrictive and liberal benzodiazepine administration.

* __Take Away__: At an institutional level, a policy of restrictive intraoperative benzodiazepine use in cardiac surgery did not reduce the incidence of delirium within 72 hrs of surgery and was not associated with an increase in patient-reported intraoperative awareness, but more research is needed to determine if restricting intraoperative benzodiazepine use at the patient level can reduce incidence of postoperative delirium.

<br>

[Han; Jun 2025]()

* __Clinical Question__: 

* __Methods + Results__:

* __Take Away__:
