---
title: "Adult Cardiothoracic Anesthesiology" 
---

# 2025 - 2026

[Association Between Surgeon-Anesthesiologist Dyad Familiarity and Operative Mortality: A Retrospective Study at a Large Academic Cardiac Surgery Program; Anesth Analg 2025](https://pubmed.ncbi.nlm.nih.gov/41032461/)

* __Clinical Question__: Does increase familiarity amongst anesthesiologists and surgeons (represented as dyads) improve outcomes in patients undergoing cardiac surgery?

* __Methods + Results__: Retrospective cohort study at single center large academic medical center.. Cases covered from 2011-2024 (16811 cases). Dyads were unique pairings that worked together on cases. Primary outcome: operative mortality, secondary outcomes: surgical length, ICU LOS, hospital LOS adverse events. Higher familiarity dyads demonstrated significantly lower operative mortality and significant decreases in all other measured secondary outcomes with exception of sternal wound infections.

* __Take Away__: While the results suggest increased surgeon-anesthesiologist familiarity leads to better outcomes, better quality and multi center studies are warranted to further quantify the importance of surgeon-anesthesiologist familiarity. Demonstrates support for the idea of dedicated anesthesia teams for certain surgical subspecialties.


<br>

[Intraoperative venous congestion rather than hypotension associated w AKI after cardiac surgery: retrospective cohort; BJA 2022](https://www.bjanaesthesia.org/article/S0007-0912(22)00063-0/fulltext)

* __Clinical Question__: In adults undergoing cardiac surgery, is increased intraoperative venous congestion and/or intraoperative hypotension associated with postoperative AKI and/or AKD (acute kidney disease)?

* __Methods + Results__: Single center (hospital in China), retrospective cohort study; exposures were low MAP (≤55, ≤65, and ≤75 mmHg) and high CVP (≥12, ≥16, and ≥20 mmHg) and primary outcome was incidence of AKI and AKD; AKI was statistically associated with both hypotension and venous congestion, while AKD was statistically associated with venous congestion.

* __Take Away__: While we commonly view intraoperative hypotension as a risk factor for postoperative kidney dysfunction in cardiac surgery, it could also be beneficial to avoid intraoperative venous congestion (ie proactively treat/avoid high CVP).


<br>

[OR extubation after cardiac surgery is associated with decreased incidence of in hospital new postoperative atrial fibrillation; Journal Clinical Anesthesia, 2024](https://www.sciencedirect.com/science/article/abs/pii/S0952818024002654?via%3Dihub)

* __Clinical Question__: 

* __Methods + Results__: 

* __Take Away__: 


<br>