---
title: "Critical Care Medicine"
---

# 2023 - 2024

All sessions held in SICU Conference Room unless otherwise noted.

_Journal club activities will be split into two formats:_
<br>
_1) Evidence-based Medicine ("EBM") sessions, which review current/recent literature on a common condition or problem in critical care and,_
<br>
_2) Deep Dive sessions, which focus on nuances of study design and interpretation._

<br>

<b>Session 1: Introduction</b>

8.30.23, 1 p.m.

Moderator: Aaron Mittel, MD

[Understanding RCTs](https://adc.bmj.com/content/90/8/840)

<br>
<b>Session 2: Healthcare Disparities EBM</b>

9.18.23, 1 p.m.

Moderator: Elvedin Lukovic, MD, PhD

[Association of Race and Ethnicity with COVID-19 Test Positivity and Hospitalization Is Mediated by Socioeconomic Factors](https://www.atsjournals.org/doi/10.1513/AnnalsATS.202011-1448OC)

[Racial Bias in Pulse Oximetry Measurement](https://www.nejm.org/doi/full/10.1056/NEJMc2029240)

[Patient and Hospital Factors Associated With Differences in Mortality Rates Among Black and White US Medicare Beneficiaries Hospitalized With COVID-19 Infection](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2781182)

[Temporal Trends in Critical Care Outcomes in U.S. Minority-Serving Hospitals](https://www.atsjournals.org/doi/10.1164/rccm.201903-0623OC)

<br>
<b>Session 3: Sepsis EBM</b>

10.9.23, 1 p.m.

Moderator: Elvedin Lukovic, MD, PhD

[EGDT (Rivers)](https://www.nejm.org/doi/full/10.1056/NEJMoa010307)

[ProCESS](https://www.nejm.org/doi/full/10.1056/nejmoa1401602)

[ProMISe](https://www.nejm.org/doi/full/10.1056/nejmoa1500896)

[ARISE](https://www.nejm.org/doi/full/10.1056/NEJMoa1404380)

[ANDROMEDA-SHOCK](https://jamanetwork.com/journals/jama/fullarticle/2724361)

[Association Between US Norepinephrine Shortage and Mortality](https://jamanetwork.com/journals/jama/fullarticle/2612912)


<br>
<b>Session 4: Sepsis Deep-Dive</b>

10.23.23., 1 p.m.

Moderator: Elvedin Lukovic, MD, PhD

[Carbapenems vs Noncarbapenem as Initial Antibiotic Therapy Against Sepsis: A Nationwide Observational Study](https://journals.lww.com/ccmjournal/fulltext/2023/09000/efficacy_of_carbapenems_compared_with.12.aspx)

<br>
<b>Session 5: ARDS</b>

11.6.23, 1 p.m.

Moderator: Aaron Mittel, MD or Elvedin Lukovic, MD, PhD or Available ICU Faculy

[ARMA](https://www.nejm.org/doi/full/10.1056/nejm200005043421801)

[ALVEOLI](https://www.nejm.org/doi/full/10.1056/NEJMoa032193)

[EPVent-2](https://jamanetwork.com/journals/jama/fullarticle/2725206)

[PROSEVA](https://www.nejm.org/doi/full/10.1056/nejmoa1214103)

[ACURASYS](https://www.nejm.org/doi/full/10.1056/nejmoa1005372)

[ROSE](https://www.nejm.org/doi/full/10.1056/nejmoa1901686)

[EOLIA](https://www.nejm.org/doi/full/10.1056/NEJMoa1800385)

<br>
<b>Session 6: ARDS Deep-Dive</b>

11.20.23, 1 p.m.

Moderator: Aaron Mittel, MD

[Limiting Dynamic Driving Pressure in Patients Requiring Mechanical Ventilation](https://journals.lww.com/ccmjournal/fulltext/2023/07000/limiting_dynamic_driving_pressure_in_patients.2.aspx)

<br>
<b>Session 7: Neuro EBM</b>

12.4.23, 1 p.m.

Moderator: Elvedin Lukovic, MD, PhD or Available ICU Faculty

[Daily interruption of sedation](https://www.nejm.org/doi/full/10.1056/nejm200005183422002)

[SLEAP](https://jamanetwork.com/journals/jama/fullarticle/1380160)

[MIND-USA](https://www.nejm.org/doi/10.1056/NEJMoa1808217)

[NONSEDA](https://www.nejm.org/doi/full/10.1056/NEJMoa1906759)

[MENDS2](https://www.nejm.org/doi/full/10.1056/NEJMoa2024922)

[AID-ICU (2023)](https://www.nejm.org/doi/full/10.1056/NEJMoa2211868)


<br>
<b>Session 8: Neuro Deep-Dive</b>

12.18.23, 1 p.m.

Moderator: Aaron Mittel, MD or Elvedin Lukovic, MD, PhD

[Trial of Endovascular Thrombectomy for Large Ischemic Strokes](https://www.nejm.org/doi/10.1056/NEJMoa2214403)

[Trial of Endovascular Therapy for Acute Ischemic Stroke with Large Infarct](https://www.nejm.org/doi/full/10.1056/NEJMoa2213379)

<br>
<b>Session 9: Renal Failure and Dialysis Timing EBM</b>

TBD 2024

Moderator: TBD

[AKIKI](https://www.nejm.org/doi/full/10.1056/NEJMoa1603017)

[STARRT-AKI](https://www.nejm.org/doi/full/10.1056/nejmoa2000741)

[IDEAL-ICU](https://www.nejm.org/doi/full/10.1056/NEJMoa1803213)

[RENAL](https://www.nejm.org/doi/full/10.1056/nejmoa0902413)

[AKIKI2](https://www.thelancet.com/pdfs/journals/lancet/PIIS0140-6736(21)00350-0.pdf)

<br>
<b>Session 10: Renal Deep-Dive</b>

TBD 2024

Moderator: TBD

[Lower vs Higher Fluid Volumes in Adult Patients With Sepsis: An Updated Systematic Review With Meta-Analysis and Trial Sequential Analysis](https://www.sciencedirect.com/science/article/pii/S0012369223006372?via%3Dihub)

<br>
<b>Session 11: Oxygenation Targets in the ICU EBM</b>

TBD 2024

Moderator: TBD

[HOT-ICU](https://www.nejm.org/doi/10.1056/NEJMoa2032510)

[Oxygen-ICU](https://jamanetwork.com/journals/jama/fullarticle/2565306)

[ICU ROX](https://www.nejm.org/doi/full/10.1056/NEJMoa1903297)

[BOX](https://www.nejm.org/doi/10.1056/NEJMoa2208686)

[PILOT](https://www.nejm.org/doi/full/10.1056/NEJMoa2208415)

<br>
<b>Session 12: Oxygenation Targets Deep-Dive</b>

TBD 2024

Moderator: TBD

[Conservative versus Liberal Oxygenation Targets in Intensive Care Unit Patients (ICONIC): A Randomized Clinical Trial](https://www.atsjournals.org/doi/abs/10.1164/rccm.202303-0560OC)

<br>
<b>Session 13: Post-arrest Management</b>

TBD 2024

Moderator: TBD

[HACA](https://www.nejm.org/doi/full/10.1056/nejmoa012689)

[Tracheal intubation and survival](https://jamanetwork.com/journals/jama/fullarticle/2598717)

[TTM](https://www.nejm.org/doi/full/10.1056/NEJMoa1310519)

[HYPERION](https://www.nejm.org/doi/10.1056/NEJMoa1906661)

[TTM2](https://www.nejm.org/doi/full/10.1056/NEJMoa2100591)

[CAPITAL CHILL](https://jamanetwork.com/journals/jama/fullarticle/2785263)

<br>
<b>Session 14: Cardiac Arrest Deep-Dive</b>

[Extracorporeal Life Support in Infarct-Related Cardiogenic Shock](https://www.nejm.org/doi/full/10.1056/NEJMoa2307227)

<br>
<b>Session 15: Steroids for Distributive Shock EBM</b>

TBD 2024

Moderator: TBD

[Annane Steroid Trial](https://jamanetwork.com/journals/jama/fullarticle/195197)

[CORTICUS](https://www.nejm.org/doi/full/10.1056/NEJMoa071366)

[ADRENAL](https://www.nejm.org/doi/full/10.1056/NEJMoa1705835)

[APROCCHSS](https://www.nejm.org/doi/full/10.1056/NEJMoa1705716)

[VITAMINS](https://jamanetwork.com/journals/jama/fullarticle/2759414)

<br>
<b>Session 16: Endocrine Deep-Dive</b>

TBD 2024

Moderator: TBD

[Thiamine for Renal Protection in Septic Shock (TRPSS): A Randomized, Placebo-controlled, Clinical Trial](https://www.atsjournals.org/doi/full/10.1164/rccm.202301-0034OC)

<br>
<b>Session 17: Nutrition</b>

TBD 2024

Moderator: TBD

[TARGET](https://www.nejm.org/doi/full/10.1056/NEJMoa1811687)

[PermiT](https://www.nejm.org/doi/full/10.1056/NEJMoa1502826)

[EPANIC](https://www.nejm.org/doi/full/10.1056/NEJMoa1102662)

[EDEN](https://jamanetwork.com/journals/jama/fullarticle/1355969)

[Optimisation of energy provision with supplementary parenteral nutrition](https://www.sciencedirect.com/science/article/pii/S0140673612613518?via%3Dihub)


<br>
<b>Session 18: Nutrition Deep-Dive</b>

TBD 2024

Moderator: TBD

[Early enteral nutrition is associated with improved outcomes in critically ill mechanically ventilated medical and surgical patients](https://www.sciencedirect.com/science/article/pii/S2405457723005338?via%3Dihub)

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-63NPTTVTEF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-63NPTTVTEF');
</script>