---
title: "Critical Care Medicine"
---

# 2025 - 2026

Journal club activities will be held on Wednesday afternoons throughout the Academic Year (August 1, 2025 through July 30, 2026). These will be ~90 minute sessions structured as outlined below. We will take a break between "EBM" and "Deep Dive" components, time permitting.

All sessions held in Presbyterian Hospital 5th Floor Sim Center Conference Room unless otherwise noted.

<br>

**EBM Review (45 min)**: review of papers that form the evidence base for our specialty.

<br>
_During EBM review, fellows will present assigned articles to the group. Fellows are expected to read ALL papers before each session. However, one fellow will "present" the paper in 5-6 min, with focus on broad reasons for the study, major methodologic points, abbreviated results, and potential to guide clinical practice._

<br>
**Deep Dive (30 min)**: detailed inspection of very recent paper with POTENTIAL to change future practice.

<br>
_During "Deep Dive", fellow and faculty will collectively discuss 1-2 articles in significant detail. This portion of journal club will focus on nuances of study design, including data analysis and interpretation of results. The goal of "Deep Dive" is to build fellows' skills for future study interpretation (i.e. beyond fellowship)._

<br>
<b>Session 1: Healthcare Disparities</b>

Wednesday, August 6, 2025

__Didactic__

<u>Guest Lecturer: Meghan Lane-Fall, MD, MSHP, FCCM</u>

_Professor and Chair of Anesthesiology at the Columbia University Vagelos College of Physicians and Surgeons and Anesthesiologist-in-Chief of the NewYork-Presbyterian/Columbia University Medical Center_

<br>
<b> Session 1.5: Introduction to Randomized Clinical Trials</b>

Thursday, August 7, 2025

Moderator: Aaron Mittel, MD, MSc

[Understanding Randomised Clinical Trials](https://adc.bmj.com/content/90/8/840)


<br>
<b>Session 2: Sepsis </b>

Wednesday, September 10, 2025

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[EGDT (Rivers)](https://www.nejm.org/doi/full/10.1056/NEJMoa010307)

[ProCESS, Promise, ARISE meta-analysis](https://pubmed.ncbi.nlm.nih.gov/25952825/)

[ANDROMEDA-SHOCK](https://jamanetwork.com/journals/jama/fullarticle/2724361)

[Association Between US Norepinephrine Shortage and Mortality](https://jamanetwork.com/journals/jama/fullarticle/2612912)

_Deep Dive_

[Prolonged infusion of beta-lactam antibiotics and short-term mortality META-ANALYSIS](https://www.sciencedirect.com/science/article/pii/S2213716525001730?via%3Dihub)

[Iloprost for Severe Septic Shock with Persistent Hypoperfusion RCT, AJRCCM 2024](https://www.atsjournals.org/doi/full/10.1164/rccm.202410-1924OC)


<br>
<b>Session 3: Observational Research</b>

Wednesday, October 8, 2025

<u>Guest Lecturer: May Hua, MD, MSc</u>

_Associate Professor of Anesthesiology (in Epidemiology) at CUMC_

_Didactic ... and ... Deep Dive_

[Comparative Effectiveness of Fludrocortisone and Hydrocortisone vs Hydrocortisone Alone Among Patients With Septic Shock](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2802801)

<br>

<b>Session 4: Respiratory Failure</b>

Wednesday, November 12, 2025

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[ARMA](https://www.nejm.org/doi/full/10.1056/nejm200005043421801)

[ALVEOLI](https://www.nejm.org/doi/full/10.1056/NEJMoa032193)

[EPVent-2](https://jamanetwork.com/journals/jama/fullarticle/2725206)

[PROSEVA](https://www.nejm.org/doi/full/10.1056/nejmoa1214103)

[ACURASYS](https://www.nejm.org/doi/full/10.1056/nejmoa1005372)

[ROSE](https://www.nejm.org/doi/full/10.1056/nejmoa1901686)

[EOLIA](https://www.nejm.org/doi/full/10.1056/NEJMoa1800385)

_Deep Dive:_

[PROMIZING RCT, NEJM, 2025](https://www.nejm.org/doi/10.1056/NEJMoa2505708)

<br>
<b>Session 5: Oxygen Use in the ICU</b>

Wednesday, December 10, 2025

Moderator: Aaron Mittel, MD, MSc

_EBM papers:_

[Oxygen-ICU](https://jamanetwork.com/journals/jama/fullarticle/2565306)

[ICU ROX](https://www.nejm.org/doi/full/10.1056/NEJMoa1903297)

[HOT-ICU](https://www.nejm.org/doi/10.1056/NEJMoa2032510)

[BOX](https://www.nejm.org/doi/10.1056/NEJMoa2208686)

[PILOT](https://www.nejm.org/doi/full/10.1056/NEJMoa2208415)

[ICONIC](https://www.atsjournals.org/doi/abs/10.1164/rccm.202303-0560OC)

_Deep Dive:_

[UK-ROX, JAMA, 2025](https://jamanetwork.com/journals/jama/fullarticle/2835384)

[UK-ROX Editorial](https://jamanetwork.com/journals/jama/fullarticle/2835385)

<br>
<b>Session 6: Sedatives</b>

Wednesday, January 14, 2026

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[Daily interruption of sedation](https://www.nejm.org/doi/full/10.1056/nejm200005183422002)

[SLEAP](https://jamanetwork.com/journals/jama/fullarticle/1380160)

[NONSEDA](https://www.nejm.org/doi/full/10.1056/NEJMoa1906759)

[AID-ICU](https://www.nejm.org/doi/full/10.1056/NEJMoa2211868)

[MIND-USA](https://www.nejm.org/doi/10.1056/NEJMoa1808217)

[Antipsychotics and the QTc Interval During Delirium in the ICU: Secondary Analysis](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2814118)

_Deep Dive:_

[A2B RCT, JAMA, 2025](https://jamanetwork.com/journals/jama/fullarticle/2834276)

[A2B Editorial](https://jamanetwork.com/journals/jama/fullarticle/2834277)
<br>

<br>
<b>Session 7: Mechanical Circulatory Support</b>

Wednesday, February 18, 2026

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[ECLS-SHOCK](https://www.nejm.org/doi/full/10.1056/NEJMoa2307227)

[IABP for Cardiogenic Shock](https://www.nejm.org/doi/full/10.1056/NEJMoa1208410)

[eCPR for OHCA](https://www.nejm.org/doi/full/10.1056/NEJMoa2204511)

[ARREST](https://www.thelancet.com/article/S0140-6736(20)32338-2/fulltext)

[MOMENTUM 3, Five-year outcomes](https://jamanetwork.com/journals/jama/fullarticle/2796306)

[DanGer Shock](https://www.nejm.org/doi/full/10.1056/NEJMoa2312572)

_Deep Dive:_

[High normocapnia and functional outcome in VA-ECMO after OCHA, Chest, 2025](https://journal.chestnet.org/article/S0012-3692(25)00062-5/fulltext)

<br>
<b>Session 8: Renal Failure</b>

Wednesday, March 18, 2026

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[AKIKI](https://www.nejm.org/doi/full/10.1056/NEJMoa1603017)

[STARRT-AKI](https://www.nejm.org/doi/full/10.1056/nejmoa2000741)

[IDEAL-ICU](https://www.nejm.org/doi/full/10.1056/NEJMoa1803213)

[RENAL](https://www.nejm.org/doi/full/10.1056/nejmoa0902413)

[AKIKI2](https://www.thelancet.com/pdfs/journals/lancet/PIIS0140-6736(21)00350-0.pdf)

_Deep Dive:_

[Early vs Standard RRT after type A aortic dissection, ATS, 2025](https://www.annalsthoracicsurgery.org/article/S0003-4975(25)00003-7/fulltext)


<br>
<b>Session 9: Nutrition</b>

Wednesday, April 15, 2026

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[TARGET](https://www.nejm.org/doi/full/10.1056/NEJMoa1811687)

[PermiT](https://www.nejm.org/doi/full/10.1056/NEJMoa1502826)

[EPANIC](https://www.nejm.org/doi/full/10.1056/NEJMoa1102662)

[EDEN](https://jamanetwork.com/journals/jama/fullarticle/1355969)

[Optimisation of energy provision with supplementary parenteral nutrition](https://www.sciencedirect.com/science/article/pii/S0140673612613518?via%3Dihub)

_Deep Dive:_

[TARGET Protein, JAMA, 2025](https://jamanetwork.com/journals/jama/fullarticle/2835302)


<br>
<b>Session 10: IV Fluids</b>

Wednesday, May 13, 2026

Moderator: Elvedin Lukovic, MD, PhD

_EBM papers:_

[SAFE](https://www.nejm.org/doi/full/10.1056/nejmoa040232)

[SMART](https://www.nejm.org/doi/full/10.1056/nejmoa1711584)

[CRISTAL](https://jamanetwork.com/journals/jama/fullarticle/1752245)

[ALBIOS](https://www.nejm.org/doi/full/10.1056/nejmoa1305727)

[HES vs. saline](https://www.nejm.org/doi/full/10.1056/NEJMoa1209759)

_Deep Dive:_

[FLUID, NEJM, 2025](https://www.nejm.org/doi/10.1056/NEJMoa2416761)


<br>
<b>Session 11: Fellow Choice - Topic TBD</b>

Wednesday, Jun 10, 2026

Moderator: Elvedin Lukovic, MD, PhD

_Deep Dive TBD_


<br>
<b>Session 12: Make-up Session</b>

TBD in case of cancellation of prior sessions

Wednesday, July 15, 2026

Moderator: Elvedin Lukovic, MD, PhD